version: '3'
services:
        api:
                ports:
                        - "8080:8080"
                image:
                        "csci4950tgt/api"

        database:
                image: postgres
                restart: always
                environment:
                        POSTGRES_PASSWORD: example
